version: '3.7'

services:

  db:
    image: postgres:13
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: "123456"
      POSTGRES_DB: timemaster_dev
    volumes:
      - pgdata:/var/lib/postgresql/data
  
  phoenix:
    build:
      context: ./timemaster
      dockerfile: Dockerfile
    volumes:
      - ./timemaster:/app
      - /app/deps
    ports:
      - "4000:4000"
    depends_on:
      - db
    environment:
      MIX_ENV: dev

  front:
    build:
      context: ./front
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
    depends_on:
      - phoenix
    environment:
      VITE_ENV: DEV
      VITE_URL_DEV: http://63.250.57.169:4000/
      VITE_URL_PROD: "*/*"
      VITE_BASE_URI: "api/"


volumes:
  pgdata: