name: Deploy to SSH Server

on:
  push:
    branches: ["deployment"]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install SSH key
        run: |
          echo "$SSH_PRIVATE_KEY" > ssh_key
          chmod 600 ssh_key
          eval $(ssh-agent)
          ssh-add ssh_key
        env:
          SSH_PRIVATE_KEY: |
            -----BEGIN OPENSSH PRIVATE KEY-----
            b3BlbnNzaC1rZXktdjEAAAAABG5vbmUAAAAEbm9uZQAAAAAAAAABAAABlwAAAAdzc2gtcn
            NhAAAAAwEAAQAAAYEAw4gWfwlAvziUCvl0/oU/4pCrcZPGQldtDFoFNNgBkEG/TEe2wAQ5
            mmTgNlcU8flm4KVAsWJHb4bae8CzbYQLDI0WSsXLLHpgGHpju6QCoZ118RLNkIApi8r9eq
            0j40JOgltKxrgW8U1t5MPmQ+lTgZ3I1zUoLQgyNuxKC8vCJJ4yOzWo9HvC3IHeJWyYWj/Y
            Yn3p2YLg9vjctYlkU3pBOfb94rDNBcteIc5DtUQ4l9c9QcjIHnfeVQ/ThlvoY32hezC0rE
            HgonLriKPapPcZfD0VLVba/uY58rXS/H23lalX0lM6DxAhi2cZwbWFtXhETXNCwXdlEK+q
            ntRpc4AB6laksAIpEUnOzAAbAlSl6fLtj2yC50cG9qSuyiilY7it2/rP2a+Osbo0c1ARYa
            vYrKQeKosYf1pmRKH7X7A2CYkwxpT56l/kh9XJh/XSR/4uvUjMu+aVqhIqMb2+qGtQtXHH
            q+GA7znySbywGard4OLwpWCDB8mrm3AWRX+7wQe3AAAFqHmrYyF5q2MhAAAAB3NzaC1yc2
            EAAAGBAMOIFn8JQL84lAr5dP6FP+KQq3GTxkJXbQxaBTTYAZBBv0xHtsAEOZpk4DZXFPH5
            ZuClQLFiR2+G2nvAs22ECwyNFkrFyyx6YBh6Y7ukAqGddfESzZCAKYvK/XqtI+NCToJbSs
            a4FvFNbeTD5kPpU4GdyNc1KC0IMjbsSgvLwiSeMjs1qPR7wtyB3iVsmFo/2GJ96dmC4Pb4
            3LWJZFN6QTn2/eKwzQXLXiHOQ7VEOJfXPUHIyB533lUP04Zb6GN9oXswtKxB4KJy64ij2q
            T3GXw9FS1W2v7mOfK10vx9t5WpV9JTOg8QIYtnGcG1hbV4RE1zQsF3ZRCvqp7UaXOAAepW
            pLACKRFJzswAGwJUpeny7Y9sgudHBvakrsoopWO4rdv6z9mvjrG6NHNQEWGr2KykHiqLGH
            9aZkSh+1+wNgmJMMaU+epf5IfVyYf10kf+Lr1IzLvmlaoSKjG9vqhrULVxx6vhgO858km8
            sBmq3eDi8KVggwfJq5twFkV/u8EHtwAAAAMBAAEAAAGAfaIqOjO6y2LSFH8WQhdh5fRohB
            CcGbJM2dvZbou/7W2hOaT2ckgErwRT3/Zx+cvy4zKq746jMbCnH07AuwRViRn6Ec8m7Ywv
            xGqXPFB0dF1VE7GuLUN77lteJP2sim/nO/Dmiepsq1zB2HRatpXr1uOH0WdRSiXzBcErDo
            s8UgTnZ43h4jzHBqHXF5rABXTyVs5qfByQ6X8baPU/ZjeuQ01E8ewBv9BcykHa1VRhPIbK
            0ELu+kywqV0C31icZ5inEjZm2WQNYtvVwh4E1ymNmGUwP7omkPBI4LXNQBDz28vHjd5r0I
            Vr2xkcspEeVYPc0rs56bjmcVDkPyj5wPy3dUdLzbVLthxeNlHoej5jnqZBVh6zYMUAfYp/
            ux4Op2WPbxMpGBfA+rvXWMkfgBYo3NExgkwKtkid+BmtXgdLSPDjWEm0R/NNrvPZMs/OVw
            PAiCSZ+iLPeNvlAVPc44BK317n4lp4l6E/RsbVyTVtFETHuR/q+35768d7TZe7B5BhAAAA
            wBrnS2U65Dne7OdJufvSEK9eToVk38mxZd3ckhGtfY3qHO98dYv5QAJ1YI97K56WLrdRO8
            T0SI4k6ocxehqXjO/iBLg+Be+l8l661sfbZSwxq3ZfkvIfQ3Zkjp0LsVnL5/inqByb/e+E
            toAJcyXYq2/b3TczpqssEJhjKcbhq6lMkV5icSQCp+ejcBH6A3PBZSEdDGYB1IhvAnCa2
            JTCNRM6+K5VqeHn4VO7rjv8gvj3fCd0EK2lLpBGerWzIew7gAAAMEA67ejCmt/Ra39z5bl
            cwcnCE3c3tNZ0oLIz8KcAKPOikZCd4AGh1VoVo168Wu3m2CsJ5p6ptFf/R7c+Y8s4kTLHxh
            RSuAs3FnbdjYnIIUCQlJmY3OEKUQMVIxCTNIjEPX0w/wPZ3rbn30W0J+cmXYh9rDEruvrE
            mivNeqnCrO5Y+ZllPLpfeG1am16uFrQ1KhMTuMkFs6XOAdSX2d2dDFg776vMv42DrSDYkK
            6x9JaNcxfk76dOLckssTcggtaKLBlRAAAAwQDUWz4feFaoMI/LpJjJ3zvn9m4VVkkhncCi
            phfJVKsdAy251zeOaKJrIu1gkVNUUvu7IlBSr1oly6/KlTB1amlyKarf5sogXslGAAAczc
            sfBg3yz4DVfU8QWVFV1xH6EFSn4yvTGNeKOFN/Tq1mSXfJw5CT6/OCbmxtyGdXeFxmtTGD
            qJ1RFAt+YZjerKXV/eG1BxGtbVzsD40L9L1FpElqqW3x6bbuLZto5wIBScytOiLB9q5p+Q
            7c4Cmz7h/5TocAAAAtamF5a3VtYXJwYXJ2ZWR5QE1hY0Jvb2stQWlyLWRlLWpheWt1bWFy
            LmxvY2FsAQIDBAUG
            -----END OPENSSH PRIVATE KEY-----
      - name: Copy files to SSH server
        run: scp -i ssh_key -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -r ./timemaster ./front docker-compose.yml root@63.250.57.169:/home/omc/projet

      - name: Restart Docker services on SSH server
        run: |
          ssh -i ssh_key -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null root@63.250.57.169 "cd /home/omc/projet && docker-compose down -v && docker-compose up --build -d"
